### ISSUE TITLE
Problems with ODS integrations

### ISSUE THREAD

**Issue by martinezmatias** [eclipse/repairnator#1143]
We have the follow exception: 

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/libxgboost4j7253714859102615054.so: libgomp.so.1: cannot open shared object file: No such file or directory
at java.lang.ClassLoader$NativeLibrary.load(Native Method)
at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
at java.lang.Runtime.load0(Runtime.java:809)
at java.lang.System.load(System.java:1086)
at ml.dmlc.xgboost4j.java.NativeLibLoader.loadLibraryFromJar(NativeLibLoader.java:66)
at ml.dmlc.xgboost4j.java.NativeLibLoader.smartLoad(NativeLibLoader.java:152)
at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:40)
at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:34)
at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:68)

```

This issue from the framework that throws that exception discuss about it:
https://github.com/dmlc/xgboost/issues/1879

**Comment by martinezmatias** [comment]
There, the solution proposed is:
https://github.com/dmlc/xgboost/issues/1879#issuecomment-417395272

**Comment by javierron** [comment]
Thanks Matias.

I will install this library in the docker image and tell you how it goes

**Comment by martinezmatias** [comment]
great Javier, thanks a lot!

**Comment by javierron** [comment]
The fix worked :+1:, however I bumped into another problem:

Coming references to paths that are not available if we run the pipeline as a JAR.

https://github.com/SpoonLabs/coming/blob/ef0451b97086d803bf954c539b726ca6e0f82d4e/src/main/resources/config-coming.properties#L51-L52

Is there a way to configure these?

**Comment by martinezmatias** [comment]
Yes, it's possible to configure that property from Coming:
```
ComingProperties.setProperty("ODSmodel", ....);
ComingProperties.setProperty("ODSTrainingFile", ....); 

```
(to configure the training "ODSTrainingFile" would not be now necessary)

I see two options to solve the problem.
1) The modify repairnator to include the setter of that property, in particular just before that line:
https://github.com/eclipse/repairnator/blob/fce2e26a639ad1c4684ab63cc9243e42249c4812/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/RepairPatch.java#L230
(there it would be necessary then that repairnators knows the location of the file, which could be previously download)

2) To modify Coming to read the resource from the JAR.
InputStream in = getClass().getResourceAsStream("/file.txt"); 

WDYT?

**Comment by javierron** [comment]
Option 2 makes more sense for me, but going through the code I noticed that the actual loading of the model is not done by coming itself, but instead it passes the path to the XGBoost library, which does not seem to use the "resources" interface:

https://github.com/SpoonLabs/coming/blob/127afd0d1c0626d443d051ce8f6fbab8919a20d3/src/main/java/fr/inria/coming/codefeatures/RepairnatorFeatures.java#L56-L57

That leaves us with option 1, but I think we should put the setter at the start of the pipeline, along with the rest of configuration stuff.

I can make this week a PR fixing this. In the meantime, the workaround I mentioned earlier is working :+1:

**Comment by martinezmatias** [comment]
Hi @javierron 
I have just made a PR in Coming.  Now, we can read the model from the jar.
https://github.com/SpoonLabs/coming/pull/241/files#diff-1ae1d7a9548c5e84b4dbf5099b92359ad103e8e3f224e0e2aed58ab7e4353b2eR84

I can create a new version of Coming in maven central if you need.

**Comment by javierron** [comment]
Hey @martinezmatias!

This is great! Thanks for taking care of this issue.

> I can create a new version of Coming in maven central if you need.

That would be great! That way I can go back to use the official version :+1:

**Comment by javierron** [comment]
SequencerRepair was able to find 6 patches, but while labeling the 5th one, this crash happened. I ran into a very similar problem that had to do with trailing whitespaces on files/patches. I was able to solve it it by using git apply with the --ignore-whitespaces directive. I am _almost_ sure that it is the same problem.

```18:32:30.563 [main] ERROR f.i.s.r.p.i.ProjectInspector - Exception catch while executing steps:
java.lang.RuntimeException: com.github.difflib.patch.PatchFailedException: Incorrect Chunk: the chunk content doesn't match the target
at fr.inria.spirals.repairnator.process.inspectors.RepairPatch.computeODSLabel(RepairPatch.java:235)
at fr.inria.spirals.repairnator.process.inspectors.RepairPatch.classifyByODSWithFeatures(RepairPatch.java:172)
at fr.inria.spirals.repairnator.process.step.repair.sequencer.SequencerRepair.businessExecute(SequencerRepair.java:253)
at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:348)
at fr.inria.spirals.repairnator.process.step.repair.AbstractRepairStep.execute(AbstractRepairStep.java:64)
at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:200)
at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:365)
at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:200)
at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:365)
at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:200)
at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:365)
at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:200)
at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:365)
at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:200)
at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:365)
at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:200)
at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:365)
at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:200)
at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:365)
at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:200)
at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:365)
at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:200)
at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:365)
at fr.inria.spirals.repairnator.process.inspectors.components.RunInspector4SequencerRepair.run(RunInspector4SequencerRepair.java:76)
at fr.inria.spirals.repairnator.process.inspectors.ProjectInspector.run(ProjectInspector.java:310)
at fr.inria.spirals.repairnator.pipeline.LegacyLauncher.mainProcess(LegacyLauncher.java:562)
at fr.inria.spirals.repairnator.pipeline.NoopListener.runListenerServer(NoopListener.java:32)
at fr.inria.spirals.repairnator.pipeline.LegacyLauncher.initProcess(LegacyLauncher.java:585)
at fr.inria.spirals.repairnator.pipeline.LegacyLauncher.launch(LegacyLauncher.java:590)
at fr.inria.spirals.repairnator.pipeline.Launcher.main(Launcher.java:64)
Caused by: com.github.difflib.patch.PatchFailedException: Incorrect Chunk: the chunk content doesn't match the target
at com.github.difflib.patch.Chunk.verify(Chunk.java:73)
at com.github.difflib.patch.AbstractDelta.verifyChunk(AbstractDelta.java:57)
at com.github.difflib.patch.ChangeDelta.applyTo(ChangeDelta.java:43)
at com.github.difflib.patch.Patch.applyTo(Patch.java:60)
at com.github.difflib.DiffUtils.patch(DiffUtils.java:159)
at fr.inria.spirals.repairnator.process.inspectors.RepairPatch.computeODSLabel(RepairPatch.java:227)```

**Comment by martinezmatias** [comment]
Hi @javierron 

We can maybe add into ODS a new label `NotEvaluated` which will be used when ODS produces an exception. (We could use the Unknown label, but it would be better to differentiate the case when ODS does not know the label from that one produced from a failure)

**Comment by javierron** [comment]
I found the root cause of the exception, and it has nothing to do with whitespaces after all. 

The build process of that project added license headers to the java files, shifting the line numbers picked by the log parser, then when ODS tried to analyze the patches, they were not applicable because of this shift. 

I am adding a line to the pipeline to skip this plugin by default.
